### ISSUE TITLE
Info: General comments

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#14]
Great work.  I have often played with doing something like this. 
Can you add a comment on how to use variables?  
Do you have a compiler / decompiler to go between the expanded forms to compressed forms?

**Comment by mikaelpatel** [comment]
> Can you add a comment on how to use variables?

Quick comment here. I will add to the README later. The variables are a vector of int's (0..VEC_MAX-1). The address to fetch and store are the index in that vector. 

> Do you have a compiler / decompiler to go between the expanded forms to compressed forms?

No. Nothing I would like to publish yet. This should actually be on the "issue" list.

**Comment by dpharris** [comment]
Why is there two 'no ops' chars: ',' and 'N'?

**Comment by mikaelpatel** [comment]
',' is for compacting number sequences and N is to hide handling of carriage-return :). There are actually more such as white-space.
