### ISSUE TITLE
Enhance: Compiler / decompiler

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#16]
While this sounds like a good idea, and might make writing and understanding the scripts, it should be a secondary project -- it has a good chance of quickly complicating this project.

**Comment by mikaelpatel** [comment]
I would like to avoid any extra tools on host. There is just too much configuration, etc. It is possible to write a simple translator that runs on the Arduino. That would be just another example sketch :)

**Comment by dpharris** [comment]
Agree :-)
