### ISSUE TITLE
Enhance: HEX number literals

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#17]
How can hex be entered?  Suggestion might use X:  X5ef,Xa5+.

(Would have preferred x, and X for execute.)

**Comment by mikaelpatel** [comment]
Right now it is only decimal format but I planned to add the traditional C-style with 0x and 0b. This increases the foot-print but will be needed. Also I would like the cell width to be configurable (int as now or long).

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/8ba71a0e052fce20e2940eb910345b819f2ee919.

**Comment by dpharris** [comment]
Yes, just saw it in the code!

**Comment by mikaelpatel** [comment]
The current implementation has a few short-cuts. It is possible to give 0b12345, i.e. binary base does not check the character set. I will get back to this later on.

**Comment by mikaelpatel** [comment]
Hexadecimal should be working fine so I will close this issue.

**Comment by mikaelpatel** [comment]
Commit https://github.com/mikaelpatel/Arduino-Shell/commit/2f19d35a2caea6c5ac62a84b2b476b8c7f4f3b9d fixes the issue with accepting illegal digits in binary base.
