### ISSUE TITLE
Question: Stack markers

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#19]
I am not sure I fully understand stack markers [].
`[6 34$I]`
would read 6 bytes from I2C device 34, and leaves 6 items on the stack with a count 6 on top, useful for future processing.  

How does that differ from just:
`6 34 $I 6`
?
I will go and reread PS (last time 25 yrs ago!).

**Comment by mikaelpatel** [comment]
No difference at all until you start using functions with variable number of parameters or return values.

**Comment by mikaelpatel** [comment]
PS syntax for array is [...]. Behind this is the functions **mark**, **counttomark** and allocation of the array. I have "used" [ as mark, and ] as counttomark. A simplification for stack based vectors (and with the new stack direction, from top stack to bottom in memory).
