### ISSUE TITLE
Enhance: Allow separate input and output streams

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Arduino-Shell#3]

**Comment by mikaelpatel** [comment]
Arduino Stream is input/output. The Print interface is output. This makes it difficult to achieve both input only.

**Comment by dpharris** [comment]
What were you hoping to achieve?

Many mpus have multiple serial interfaces.  I would think applications
might want to send and receive on one of those, but direct errors to the
default serial.  This may be a use for trap functions, or builtin ones: `.
`v `k`m etc to use alternate serial or even `.n`vn `kn`mn to use nth
serial interface.

I think it would be good to make those optional.

**Comment by mikaelpatel** [comment]
The idea behind this was to create stream handling a bit like C/C++ with stdin, stdout and stderr. And allow binding to different Arduino Stream classes. 

This has been put on the to-do-later list as there is too little usage to go on right now.

**Comment by dpharris** [comment]
Agree.  Should be optional addition.
