### ISSUE TITLE
Bug: ShellDemo doesn't appear to work.

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#30]
The other demos appear to work fine.

**Comment by mikaelpatel** [comment]
Do you have any more info? Does not compile?

**Comment by dpharris** [comment]
Yes, compiles, prints welcome.  Seems to fail on the iom.read() step.
Never makes it to the (added) print(bp):
void loop()
{
  Serial.println(".");   // works (added)
  if (shell.read(bp)) {
    Serial.print("==>"); Serial.println(bp);  // never gets here (added)
    shell.execute(buf);
    bp = buf;
  }
  delay(500);  // (added)
}

**Comment by mikaelpatel** [comment]
What board are you using? I tested on Uno and Mega without any problem.

**Comment by mikaelpatel** [comment]
Should try Serial.println(buf) instead. bp points to the end of the input line (0).

**Comment by mikaelpatel** [comment]
Serial Monitor must be in [Newline] mode.

**Comment by dpharris** [comment]
Oh, I think I turned that off .....

**Comment by dpharris** [comment]
Yes, that was the problem!   Thanks ... will need to note that.  
(( I had forgotten I had disabled it for another program I was working on)).
David

**Comment by mikaelpatel** [comment]
Added some startup info about the [Newline] mode in the example sketches that use read().
