### ISSUE TITLE
Enhance: Improved loop control structure

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Arduino-Shell#31]
The loop control structure could be improved to:

```
low high { loop-block } loop
```

And the loop block should receive the current index as top of stack.

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/e6f910e5ef395a626d02e8af9dd5c7128099c5ff.

**Comment by dpharris** [comment]
nice!
