### ISSUE TITLE
Enhance: Define named scripts in sketch (C++)

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Arduino-Shell#32]
It should be possible to set a variable or function from the sketch. This allows the application to define a set of scripts.

```
shell.set(name, value);
shell.set(name, script);
```

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/e6f910e5ef395a626d02e8af9dd5c7128099c5ff, https://github.com/mikaelpatel/Arduino-Shell/commit/ebcbb009f94d36e2fe8e204f980f8a595fa902dd and https://github.com/mikaelpatel/Arduino-Shell/commit/c334928a0e105be678b2fa93b65670ea688a8f20.

**Comment by dpharris** [comment]
How about loading the stack before running the script?  
Can I do: 
   shell.push(0); shell.push(4); shell.execute(script0);

**Comment by mikaelpatel** [comment]
That has been available for a while now :).

**Comment by mikaelpatel** [comment]
Allow scripts from SRAM and PROGMEM to be set. Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/dfa2fc5d89ec6461a474555ed1942681c839e35a.
