### ISSUE TITLE
Bug: Stack Vector Sum example broken

### ISSUE THREAD

**Issue by dpharris** [mikaelpatel/Arduino-Shell#38]
Your change to loops broke the example.

This works:
      [1,2,3] 0 1 rotate { drop + } loop
   or: 
      [1,2,3]0,1r{d+}l

A larger list is nicer: [1,2,3,4,5,6,7,8]0,1r{d+}l

**Comment by mikaelpatel** [comment]
Yes, forgot that. Thanks for the reminder.

**Comment by mikaelpatel** [comment]
Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/85df422a4cab6616321b9c4f77bacaa8fb77a9ae.
