### ISSUE TITLE
Enhance: Allow scripts in PROGMEM and/or EEMEM

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Arduino-Shell#6]

**Comment by dpharris** [comment]
This would seem to be a good extension.

**Comment by mikaelpatel** [comment]
Some example code in [ShellScript](https://github.com/mikaelpatel/Arduino-Shell/blob/master/examples/ShellScript/ShellScript.ino). Uses a buffer and copies scripts from PROGMEM to the buffer before calling the shell. The pattern can be used to reduce SRAM for scripts. Only the command line buffer is needed.

**Comment by mikaelpatel** [comment]
Allowing scripts in program memory is an interesting challenge. One solution is to synthesis a combined address space so that the virtual machine can detect if the script is in random access or program memory. Please see commit https://github.com/mikaelpatel/Arduino-Shell/commit/f6f471b66080d9801be6d946c4cbfae0270ff9b7.

**Comment by dpharris** [comment]
Nice!
